top_srcdir   = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
top_builddir = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
srcdir       = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/os
builddir     = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/os
VPATH        = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
