top_srcdir   = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
top_builddir = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
srcdir       = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/aaa
builddir     = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/aaa
VPATH        = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/aaa

include $(top_srcdir)/build/special.mk

