top_srcdir   = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
top_builddir = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
srcdir       = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/filters
builddir     = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/filters
VPATH        = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/filters

include $(top_srcdir)/build/special.mk

