top_srcdir   = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
top_builddir = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
srcdir       = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/mappers
builddir     = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/mappers
VPATH        = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/mappers

include $(top_srcdir)/build/special.mk

