top_srcdir   = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
top_builddir = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
srcdir       = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/server/mpm/prefork
builddir     = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/server/mpm/prefork
VPATH        = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
