top_srcdir   = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
top_builddir = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
srcdir       = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/experimental
builddir     = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/experimental
VPATH        = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/modules/experimental
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
