top_srcdir   = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
top_builddir = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17
srcdir       = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/server/mpm
builddir     = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/server/mpm
VPATH        = /homes/xiao67/cs390/CS390-Py/httpd-2.2.17/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
